// DATA GLOBAL
export const MARVEL_GLOBAL = "MARVEL_GLOBAL";
export const OBJECT_HEROE = "OBJECT_HEROE";
// PELEAS
export const AGREGAR_NRO_PELEAS = "AGREGAR_NRO_PELEAS";
export const LUCHADORES = "LUCHADORES";
// RANKING
export const LUCHADOR_RANKING = "LUCHADOR_RANKING"